language: node_js
node_js:
- stable
- '0.12'
before_install:
- sudo apt-get update
- sudo apt-get install python-software-properties
- sudo add-apt-repository ppa:ondrej/php5 -y
- sudo apt-get update
- sudo apt-get install php5
- sudo apt-get install php5-curl
- php --version
- php -r "readfile('https://getcomposer.org/installer');" | php
- travis_retry php composer.phar config --global github-oauth.github.com $COMPOSER_AUTH
- travis_retry php composer.phar config --global --list
- gem update --system
- gem install sass --version "=3.3.7"
- npm cache clean
- npm update -g npm
- npm install -g bower grunt-cli jspm
- jspm config registries.github.auth $JSPM_AUTH
- currentfolder=${PWD##*/}
- if [ "$currentfolder" != 'generator-grunt-symfony' ]; then cd .. && eval "mv $currentfolder generator-grunt-symfony" && cd generator-grunt-symfony; fi
